name: gitwp
description: gitwp
runs:
  using: 'docker'
  image: 'docker/Dockerfile'
  args:
  - test
  env:
    WORDPRESS_DB_HOST: 'mysql:3306'
    WORDPRESS_DB_USER: mysql
    WORDPRESS_DB_PASSWORD: mysql
    WORDPRESS_DB_NAME: wordpress
