name: gitwp
description: gitwp
runs:
  using: 'docker'
  image: 'docker/Dockerfile'
  args:
  - test
  env:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_USER: mysql
    WORDPRESS_DB_PASSWORD: ''
    WORDPRESS_DB_NAME: wordpress
