name: gitwp
description: gitwp
inputs:
  test_path:
    default: ""
    description: "A specific path (other than repo root) to run the tests on"
    required: false
runs:
  using: 'docker'
  image: 'docker/Dockerfile'
  args:
  - test
  env:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: ''
    WORDPRESS_DB_NAME: wordpress
    GITWP_TEST_PATH: ${{ inputs.test_path }}
