name: gitwp
description: gitwp
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - test
  env:
    WORDPRESS_DB_HOST: localhost
    WORDPRESS_DB_USER: mysql
    WORDPRESS_DB_PASSWORD: mysql
    WORDPRESS_DB_NAME: wordpress
